# Generated by Django 4.2.23 on 2025-10-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='session_title',
            field=models.CharField(choices=[('Design Strategy', 'Design Strategy'), ('Photography Critique', 'Photography Critique'), ('Brand Foundations', 'Brand Foundations')], max_length=120),
        ),
    ]
