# Generated by Django 4.2.23 on 2025-11-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_session_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('scheduled_at',), name='unique_timeslot_global'),
        ),
    ]
